### PR TITLE
showing report view when game is finished

### LINKED ISSUE #62: wrong view when joining game while finished
when I try to join a game while it is already finished, but not yet started, the user stays on the guess site with a 0 countdown. the user should see the report view.

### PR DESCRIPTION
**Pull request by holzeis**
resolves #62

### CODE REVIEW

File: app/hangman/game.coffee [hunk 1]
```diff
@@ -67,18 +75,24 @@ class exports.Game
...
 		, @countdown * 1000, @
 
 	stop: () ->
 		@io.log.info "stopping " + @name
+		@countdown = 0
 		for socket in @io.clients @name
 			socket.game.guess.length = 0
 			socket.emit 'stop'
 
 	report: (player) ->
```
Comment (bonomat) [inline app/hangman/game.coffee]: might be better to use a callback instead of a return value, e.g. if generating a report involves some computations and takes some time

Comment (holzeis) [inline app/hangman/game.coffee]: good idea, but needs to be considered for all game events. i'll open an issue for that.
